# NB: This is the cucumber config yaml for the performance_test gem integration test

<%
require 'fileutils'
FileUtils.mkdir_p(File.join 'target', 'reports')
%>

performance: >
  --require features/step_definitions 
  --require lib/performance_test/performance_test_steps.rb 
  --format pretty 
  --format html 
  --out target/reports/integration-test.html
